# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.7.0
_src_path: gh:OCA/oca-addons-repo-template
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: false
include_wkhtmltopdf: false
odoo_version: 13.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups: []
repo_description: Server side features for usability and user experience related
repo_name: Server UX
repo_slug: server-ux
repo_website: https://github.com/OCA/server-ux
travis_apt_packages:
- libzbar-dev
- poppler-utils
travis_apt_sources: []
