[project]
name = "odoo-addons-oca-server-ux"
version = "19.0.20260907.0"
dependencies = [
    "odoo-addon-barcode_action==19.0.*",
    "odoo-addon-base_cancel_confirm==19.0.*",
    "odoo-addon-base_export_manager==19.0.*",
    "odoo-addon-base_menu_visibility_restriction==19.0.*",
    "odoo-addon-base_optional_quick_create==19.0.*",
    "odoo-addon-base_revision==19.0.*",
    "odoo-addon-base_search_custom_field_filter==19.0.*",
    "odoo-addon-base_substate==19.0.*",
    "odoo-addon-base_technical_features==19.0.*",
    "odoo-addon-date_range==19.0.*",
    "odoo-addon-date_range_account==19.0.*",
    "odoo-addon-developer_menu==19.0.*",
    "odoo-addon-document_quick_access==19.0.*",
    "odoo-addon-mail_message_destiny_link_template==19.0.*",
    "odoo-addon-sequence_reset_period==19.0.*",
    "odoo-addon-server_action_mass_edit==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
